# DMA Lab: Numpy Basics Demo Session


# Numpy

- Numpy is the core library for scientific computing in Python. 
- It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [1]:
import numpy as np

## Arrays

- A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
- The number of dimensions is the rank of the array.
- The shape of an array is a tuple of integers giving the size of the array along each dimension.

### Create a rank 1 array

In [5]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a)

print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

<class 'numpy.ndarray'>
(3,)
[1 2 3]
1 2 3
[5 2 3]


### Create a rank 2 array

In [6]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b)

print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

(2, 3)
[[1 2 3]
 [4 5 6]]
1 2 4


In [7]:
a = np.array([list(range(1,5)),[2,4,5,6],[3,4,5,6],[5,6,7,8]])

a

array([[1, 2, 3, 4],
       [2, 4, 5, 6],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [7]:


#Numpy array datatypes
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"


int64
float64
int64


In [10]:
# Numpy functions to create arrays

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"


[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.60086979 0.12386838]
 [0.58019009 0.09667012]]


## Array indexing

- Numpy offers several ways to index into arrays.

- Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array.


In [12]:
# Slice indexing
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print (b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


### Boolean array indexing 
- Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.

In [16]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)


# We can use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values of bool_idx
print(a[bool_idx])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [18]:
#Alternate way of writing above solution in a single concise statement
print(a[a > 2])

[3 4 5 6]


### Mathematical functions operating on arrays

In [19]:
# Mathematical functions operate elementwise on arrays
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [20]:
# The dot function computes inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. 
# dot is available both as a function in the numpy module and as an instance method of array objects
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [21]:
# Computing sum function of array elements

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"


10
[4 6]
[3 7]


#### Exercise 4.1

In [9]:
x = np.array([[1,2],[3,4],[5,6],[7,8]])
print(x)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [10]:
# Compute the mean by row 
## START CODE
print (np.mean(x, axis = 1))
## END CODE

[1.5 3.5 5.5 7.5]


In [ ]:
# Compute the mean by column 
## START CODE

## END CODE

In [ ]:
# Compute the mean for all the elements of the array
## START CODE

## END CODE

In [22]:
# Transposing an array
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### Reshaping
- The reshape gives a new shape to an array without changing its data. 
- It creates a new array and does not modify the original array itself. 

In [15]:
# Reshaping an array
x = np.linspace(1, 8, num=8)      # Creates an array of 8 numbers (num=8) in the range (1,8) 
print(x)
print(x.shape)

# Create a 2D array of shape (4,2) from x
y = x.reshape((4,2))
print(y)
print(y.shape)

[1. 2. 3. 4. 5. 6. 7. 8.]
(8,)
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
(4, 2)


## Broadcasting

In [5]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(x)
print(v)
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


#### Exercise 4.2 - Functions

In [11]:
import numpy as np
def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    s = 1/(1 + np.exp(-x))
    
    return s

In [12]:
x = np.array([1, 2, 3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

#### Exercise 4.3

Print a reversed NumPy array with the element type float.

*Input Format*

- A single line of input containing space separated numbers.

*Output Format*

- Print the reverse NumPy array with type float.

*Sample Input*

1 2 3 4 -8 -10

*Sample Output*

[-10.  -8.   4.   3.   2.   1.]


In [14]:
## Start code
ls = [1,2,3,4,-8,-10]
arr = np.array(ls[::-1], dtype=float)
arr
## End code

array([-10.,  -8.,   4.,   3.,   2.,   1.])

## Reference on Numpy for more details
    - https://docs.scipy.org/doc/numpy/reference/