In [ ]:
import numpy as np


## Basic data types

In [ ]:
# Numbers: Integers and floats 
x = 3
print(type(x))                         # Prints "<class 'int'>"
print(x)                               # Prints "3"
print(x + 1)                           # Addition; prints "4"
print(x - 1)                           # Subtraction; prints "2"
print(x * 2)                           # Multiplication; prints "6"
print(x ** 2)                          # Exponentiation; prints "9"
x += 1
print(x)                               # Prints "4"
x *= 2
print(x)                               # Prints "8"
y = 2.5
print(type(y))                         # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2)         # Prints "2.5 3.5 5.0 6.25"


In [ ]:
# Booleans
t = True
f = False
print(type(t))         # Prints "<class 'bool'>"
print(t and f)         # Logical AND; prints "False"
print(t or f)          # Logical OR; prints "True"
print(not t)           # Logical NOT; prints "False"
print(t != f)          # Logical XOR; prints "True"


In [ ]:
# Strings
hello = 'hello'                         # String literals can use single quotes
world = "world"                         # or double quotes; it does not matter.
print(hello)                            # Prints "hello"
print(len(hello))                       # String length; prints "5"
hw = hello + ' ' + world                # String concatenation
print(hw)                               # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)                             # prints "hello world 12"


In [ ]:
# String methods: For more visit https://docs.python.org/3.5/library/stdtypes.html#string-methods
s = "hello"
print(s.capitalize())             # Capitalize a string; prints "Hello"
print(s.upper())                  # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))                 # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))                # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))    # Replace all instances of one substring with another;
                                  # prints "he(ell)(ell)o"
print('  world '.strip())         # Strip leading and trailing whitespace; prints "world"


## Containers 
- built-in container types: lists, dictionaries, sets, and tuples.

### Lists

- A list is the Python equivalent of an array, but is resizeable and can contain elements of different types

In [ ]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"


In [ ]:
# Slicing
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"


#### Exercise 1.1

In [ ]:
# Given a=[1,2,3,4,5], slice 'a' to obtain [4, 3, 2]

a = [1,2,3,4,5]

## START CODE HERE


##END CODE HERE


In [ ]:
# Loops
animals = ['dog', 'cat', 'monkey', 'bear']

# Print the elements of the list
print("Elements before sorting:")
for animal in animals:
    print(animal)
# Prints "dog", cat", "monkey", "bear", each on its own line.

# Sort the list in ascending order
animals.sort()

print("Elements after sorting:")
for animal in animals:
    print(animal)
# Prints "bear", cat", "dog", "monkey", each on its own line.


In [ ]:
# List comprehensions: to transform one type of data into another.
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)                # Prints [0, 1, 4, 9, 16]


In [ ]:
# Alternate
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)                # Prints [0, 1, 4, 9, 16]


In [ ]:
# List comprehensions with condition
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)           # Prints "[0, 4, 16]"


#### Exercise 1.2

In [ ]:
# Read an integer N. For all non-negative integers i < N, print i^2

N = 5

## START CODE HERE



## END CODE HERE    
    

### Dictionaries

- A dictionary stores (key, value) pairs, similar to a Map in Java 

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])                      # Get an entry from a dictionary; prints "cute"
print('cat' in d)                    # Check if a dictionary has a given key; prints "True"
d['fish'] = 'wet'                    # Set an entry in a dictionary
print(d['fish'])                     # Prints "wet"
# print(d['monkey'])                 # KeyError: 'monkey' not a key of d
print(d.get('monkey', 'N/A'))        # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))          # Get an element with a default; prints "wet"
del d['fish']                        # Remove an element from a dictionary
print(d.get('fish', 'N/A'))          # "fish" is no longer a key; prints "N/A"


In [ ]:
# Loops
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"


In [ ]:
# Alternate using items()
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"


In [ ]:
# Dictionary comprehensions
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)  # Prints "{0: 0, 2: 4, 4: 16}"


#### Exercise 2.1

Concatenate the following dictionaries to create a new dictionary.

dic1={1:10, 2:20}

dic2={3:30, 4:40}

dic3={5:50,6:60}

Expected Result: {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}

In [ ]:
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}

## START CODE HERE




##END CODE HERE


### Sets

- A set is an unordered collection of distinct elements.

In [ ]:
animals = {'cat', 'dog'}
print('cat' in animals)            # Check if an element is in a set; prints "True"
print('fish' in animals)           # prints "False"
animals.add('fish')                # Add an element to a set
print('fish' in animals)           # Prints "True"
print(len(animals))                # Number of elements in a set; prints "3"
animals.add('cat')                 # Adding an element that is already in the set does nothing
print(len(animals))                # Prints "3"
animals.remove('cat')              # Remove an element from a set
print(len(animals))                # Prints "2"


In [ ]:
# Loops
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"


In [ ]:
# Set comprehensions
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)  # Prints "{0, 1, 2, 3, 4, 5}"


#### Exercise 3.1

Given the participants' score sheet for your University Sports Day, you are required to find the runner-up score. You are given n scores. Store them in a list and find the score of the runner-up.

Explanation:

Given list is [2, 3, 6, 6, 5]. The maximum score is 6, second maximum is 5. Hence, print 5 as the runner-up score. 

In [ ]:
## START CODE HERE



##END CODE HERE


### Tuples

- A tuple is an (immutable) ordered list of values. 
- A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot.

In [ ]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)                              # Create a tuple
print(type(t))                          # Prints "<class 'tuple'>"
print(d[t])                             # Prints "5"
print(d[(1, 2)])                        # Prints "1"
print (d)

#### Quiz

Which of the following statements given below is/are true?

A. Tuples have structure, lists have an order.

B. Tuples are homogeneous, lists are heterogeneous.

C. Tuples are immutable, lists are mutable.

D. All of them.

In [ ]:
## Ans: 

## Functions

- Python functions are defined using the def keyword.

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))
# Prints "negative", "zero", "positive"


In [ ]:
# define functions with optional keyword arguments
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Amar')                              # Prints "Hello, Bob"
hello('Akbar', loud=True)                  # Prints "HELLO, FRED!"


# Numpy

- Numpy is the core library for scientific computing in Python. 
- It provides a high-performance multidimensional array object, and tools for working with these arrays.

## Arrays

- A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
- The number of dimensions is the rank of the array.
- The shape of an array is a tuple of integers giving the size of the array along each dimension.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"


In [ ]:
#Numpy array datatypes
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"


In [ ]:
# Numpy functions to create arrays

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"


## Array indexing


In [ ]:
# Slice indexing
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print (b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

In [ ]:
# Mathematical functions operate elementwise on arrays
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))


In [ ]:
# The dot function computes inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. 
# dot is available both as a function in the numpy module and as an instance method of array objects
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

In [ ]:
# Computing sum function of array elements

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"


#### Exercise 4.1

In [ ]:
x = np.array([[1,2],[3,4],[5,6],[7,8]])
print(x)

In [ ]:
# Compute the mean by row 
## START CODE

## END CODE

In [ ]:
# Compute the mean by column 
## START CODE

## END CODE

In [ ]:
# Compute the mean for all the elements of the array
## START CODE

## END CODE

In [ ]:
# Transposing an array
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

In [ ]:
# Reshaping an array
x = np.linspace(1, 8, num=8)      # Creates an array of 8 numbers (num=8) in the range (1,8) 
print(x)
print(x.shape)

# Create a 2D array of shape (4,2) from x
x = x.reshape((4,2))
print(x)
print(x.shape)

## Broadcasting

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

## Reference on Numpy for more details
    - https://docs.scipy.org/doc/numpy/reference/

#### Exercise 4.2 - Functions

In [ ]:
import numpy as np
def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """

    
    return s

In [ ]:
x = np.array([1, 2, 3])
sigmoid(x)